version: '3.1'

services:

  app:
    container_name: miblog
    build:
      context: .
      dockerfile: dockerfiles/development.dock
    depends_on:
      - db
    environment:
      APP_VERSION: development
      MY_SERVER_NAME: https://miblog.com
      WEB_CONCURRENCY: 1
      SPAWN_METHOD: direct
      DB_HOST: db
      DB_NAME: samemoon_development
      DB_USERNAME: postgres
      DATABASE_URL: postgres://postgres:example@db:5432/samemoon_development
    ports:
      - '80:3000'
    volumes:
      - ./:/webapps/miblog/

  db:
    container_name: miblog_db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example


